version: "3.9"
services:
  app:
    image: node:16
    command: yarn run dev
    ports:
      - 3000:3000
    working_dir: /app
    user: "1000:1000"
    volumes:
      - ./:/app
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: plorium
      POSTGRES_PASSWORD: plorium
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  dbdata:
